sudo: required

language: java

jdk:
  - oraclejdk8

os:
  - linux
  - osx

osx_image: xcode9.3

services:
  - docker

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

branches:
  except:
    - gh-pages
    - docs

<<<<<<<<< Temporary merge branch 1
before_deploy:
  - "./gradlew assembleDist"

deploy:
  - provider: releases
    api_key: $GITHUB_API_KEY
    skip_cleanup: true
    draft: true
    file_glob: true
    file:
      - build/distributions/*.tar
      - build/distributions/*.zip
    on:
      branch: release
      tags: true

stages:
  - build
  - test
  - deploy

jobs:
  include:
    - stage: build
      name: "Build"
      script: ./gradlew assemble

    - stage: test
      name: "Test"
      script: ./gradlew check

    - stage: deploy
      os: linux
      if: tag = true
      name: "Github Releases"
      script: skip
      before_deploy: "./gradlew assembleDist"
      deploy:
        - provider: releases
          api_key: $GITHUB_API_KEY
          skip_cleanup: true
          draft: true
          file_glob: true
          file:
            - build/distributions/*.tar
            - build/distributions/*.zip
          on:
            branch: release
            tags: true

    - script: '.travis/docker-push'
      os: linux
      if: env(TRAVIS_EVENT_TYPE) = cron OR tag = true
      before_script: chmod +x .travis/docker-push
      name: "Docker Image"
